### PR TITLE
Creates CodingResources html file. TK

### PR DESCRIPTION
**Pull request by camilyo**
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Coding and Resources</title>
  </head>
  <body>
     <h3>Coding and Resorces</h3>
     <p> If you want to be a developer or programmer, you need to be able to do coding.
      So, we could say it is more important to do actually coding than just thinking.
      Then, what should we do first? We need to know what programming language is and choose which programming language we want to learn. </p>
     <h4>What is programming language ?</h4>
    <p>Computer programming languages allow users to give some instructions to their computers,
      make computers execute what they want, and finally solve problems using algorithms in computers.
      There are tons of programming languages including COBOL, C++, Java, or Python.</p>
    <p></p>
     <p>Also, we could also use other languages they are not considered real programming languages such as HTML, CSS, or SQL.
      HTML is a markup language, and CSS is a style sheet language. Then, SQL might be considered a data query language or database management language.
      Because those languages do not contain programming logic, many people do not think they are programming languages. In this article,
      we are talking about programming languages, so let’s put aside these languages for later.</p>
    <p></p>
     
     <h4>What is a good programming language for a beginner?</h4>
     <p>As a beginner, we need to be careful on choosing our first programming language.
      If you choose a really difficult one that you cannot follow, you might lose your interests on coding.
      There is a good article that guides you. You could check this here:</p>
    <p><a href=" http://outsoft.com/blog/which-programming-language-should-you-learn-the-infographic-to-code-it-all">
    Infographic on Programming Languages: Which One Should You Learn?</a></p>
     
     <p>This article describes 10 programming languages for a beginner: Python, JavaScript, Ruby, PHP, Java, C, C#, Objective-C, C++.
      Here are some coding examples of Java and Python.</p>
    <p></p>
   
     <p><a href=""> java coding file here</a></p>
    <p></p>
    <p><a href=""> python coding file here</a></p>
    <p></p>
    <p>After choosing a programming language that you want to code, you need to find how or where to learn and code.
      In this article, let’s choose Java and check how to code in Java.</p>
     <h5>How to learn Java coding?</h5>
    <p>You could go to a college and take some programming classes,
      but it might be still not enough to enhance or practice coding or you need an extra course that is simpler and easier doing just coding.</p>
    <p></p>
     <h6>Learning in a website</h6>
    <p>Here is good news for you! There are many websites that teach people coding step by step.
      And here is an article that you might as well read:</p>
    <p><a href=" https://www.hongkiat.com/blog/sites-to-learn-coding-online/">
    Top 10 Websites to Learn Coding (Interactively) Online.</a></p>
    <p></p>
     <p>Many of you must have heard about <a href="https://www.codecademy.com/learn/learn-java">Codecademy</a> or even used that website.
      You can try some coding of many programming languages on that websites even without installing any applications.
      Or, if you want to learn web programmings, <a href="https://teamtreehouse.com/learn/java">Treehouse</a> could be a good option.</p>
    <p></p>
     <h5>Taking a course in an online learning institution</h5>
    <p>You could also take some online courses such as from <a href="https://www.udemy.com/">Udemy</a> or
      <a href="https://www.coursera.org/courses?query=java">Coursera</a>.
      Unlike learning on Codecademy, you need to install some applications or programs first.
      In fact, if you really want to improve your coding skill, you need to install and do coding on your own computer.</p>
     <h7>What program or application do we need?</h7>
    <p>If you want to code in Java, you first have to download <a href="https://www.oracle.com/technetwork/java/javase/downloads/index.html">
    Java platform (JDK)</a> and install on your computer.
      Then, you should need Java IDEs (Integrated Development Environment). Here is an article that introduces 10 Java IDEs:
      <a href="https://beebom.com/best-java-ides-of-all-time/">10 Best Java IDEs of All Time</a>.
      Now, we check two of them, Intellij IDEA and Eclipse. Eclipse is a popular one that is an open source tool, which means it is free.
      Also, it has a great community of developers. Intellij IDEA is not a free but it has a great feature, especially debugging.
      In addition, they allow students use it for free during they enroll in a college.</p>
     <p></p>
    <h4>Now, you have everything to do coding in Java. Just do coding!</h4>
   </body>
</html>

### CODE REVIEW

**Comment by camilyo** [comment]
Hi TK, I did a little update in all your headings because in HTML you can't use the same heading twice in the same page. Everything else looks great

**Comment by tkim949** [comment]
Hey Camila. Good to hear from you. Thanks. But, unfortunately, I have trouble finding where you edited. Please highlight it for me.

**Comment by tkim949** [comment]
> Hi TK, I did a little update in all your headings because in HTML you can't use the same heading twice in the same page. Everything else looks great

Hey Camila. Good to hear from you. It looks that HTML file is working on your computer as well. That's Good! Thanks. 
But, unfortunately, I have trouble finding where you edited. Please highlight it for me.

**Comment by tkim949** [comment]
> Hi TK, I did a little update in all your headings because in HTML you can't use the same heading twice in the same page. Everything else looks great



> > Hi TK, I did a little update in all your headings because in HTML you can't use the same heading twice in the same page. Everything else looks great
> 
> Hey Camila. Good to hear from you. It looks that HTML file is working on your computer as well. That's Good! Thanks.
> But, unfortunately, I have trouble finding where you edited. Please highlight it for me.

Oh, I see. Now I can see the changes; you changed the hierarchy level, but I made them on purpose. I made several h4 levels and two h5 levels because they are of the same hierarchy level. My part is "Coding and Resources," and it has 5 upper-level subtopics and their contents which are h4 and maybe, the third subtopic has two lower-level contents, which are h5. Anyway, I heard that Chengtao will be in charge of the style and structure of our website, I mean CSS and Design.
Once again, Thank you for checking my file!

**Pull request merged**
